!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
MODULE MAIN_MODULE_DIFF
  USE BUFLOWMODULE_DIFF
  USE MESHDEFORMATIONN_DIFF
!!!!!!!!!!      
!!!!!!!!!!	 
  IMPLICIT NONE

CONTAINS
! 模块内包含子程序，自动生成显式接口
  SUBROUTINE MAIN(data_4d137, cellprimitivesout)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
!$AD &input_param          ! 标记输入
!$AD &cellPrimitives       ! 标记输出
! 输入参数：仅原data_4D137的第一个维度（标量）
    REAL(kind=8), ALLOCATABLE, INTENT(OUT) :: cellprimitivesout(:, :)
    REAL(kind=8), INTENT(IN) :: data_4d137(1, 4)
! 传递变形网格点的变量
    INTEGER(kind=8) :: ncells, meshinfo(4), iostat, nlines_points, &
&   file_unit_points, nfaces, nfaceperbdry, nboundaries, nlines_boundary&
&   , file_unit_boundary, nlines_owner, file_unit_owner, &
&   nlines_neighbour, file_unit_neighbour, nlines_faces, file_unit_faces&
&   , startline_faces, fcount, i, bracketl, bracketr, pt_count
    INTEGER(kind=8) :: bcount, startline_boundary, npoints
!        real(kind=8), allocatable :: point_update(:,:)  
    CHARACTER(len=256) :: meshpath, pointsfilepath, boundaryfilepath, &
&   ownerfilepath, neighbourfilepath, facesfilepath, line
	INTEGER(kind=8) :: n 
    REAL(kind=8), ALLOCATABLE :: b_i(:), x_tan(:), dwdx(:, :)
    REAL(kind=8), ALLOCATABLE :: ptc_res(:), ptc_dx(:), ptc_ax(:)
    REAL(kind=8) :: tol, machnum
    REAL(kind=8) :: ptc_sigma0, ptc_sigma, ptc_sigma_decay
    REAL(kind=8) :: ptc_tol_start, ptc_tol_stage
    REAL(kind=8) :: ptc_omega_stage, ptc_res_prev, ptc_res_new, bnrm_i
    INTEGER(kind=8) :: maxiter, m_restart, c, ptc_it, ptc_steps, maxiter_stage
    INTEGER :: info, i_param, info_stage
    LOGICAL :: use_tangent_ptc_outer
    REAL(kind=8), ALLOCATABLE :: rhs_rho(:, :)
    INTEGER(kind=8), SAVE :: pc_outer_counter = 0_8
	INTEGER(kind=8), PARAMETER :: pc_update_m = 4_8
    TYPE(MESHDATA) :: tempmesh
    INTRINSIC TRIM
    INTRINSIC INDEX
    INTRINSIC SIZE
    INTRINSIC MAXVAL
    INTRINSIC ALLOCATED
!!!!!!!!!!!!
!!!!!!!!!!!!
!!!!!!!!!!!!!!meshdeformation
    file_unit_points = GET_FREE_UNITT()
    meshpath = 'mesh/OFairfoilMesh'
    pointsfilepath = TRIM(meshpath)//'/points'
    OPEN(unit=file_unit_points, file=pointsfilepath, status='old', &
&  action='read', iostat=iostat) 
    nlines_points = 0
    DO 
      READ(file_unit_points, '(a)', iostat=iostat) 
      IF (iostat .NE. 0) THEN
        REWIND(file_unit_points) 
        ALLOCATE(lines_defor(nlines_points))
        boundaryfilepath = TRIM(meshpath)//'/boundary'
        file_unit_boundary = GET_FREE_UNIT()
        OPEN(unit=file_unit_boundary, file=boundaryfilepath, status=&
&      'old', action='read', iostat=iostat) 
        nlines_boundary = 0
        DO 
          READ(file_unit_boundary, '(a)', iostat=iostat) 
          IF (iostat .NE. 0) THEN
            REWIND(file_unit_boundary) 
            ALLOCATE(blines(nlines_boundary))
            DO i=1,nlines_boundary
              READ(file_unit_boundary, '(a)') blines(i)
            END DO
            CLOSE(file_unit_boundary) 
            CALL OFFILE_FINDNITEMSSS(blines, startline_boundary, bcount)
            ALLOCATE(boundarynumfacess(bcount))
            ALLOCATE(boundarystartfacess(bcount))
            ownerfilepath = TRIM(meshpath)//'/owner'
            file_unit_owner = GET_FREE_UNIT()
            OPEN(unit=file_unit_owner, file=ownerfilepath, status='old'&
&          , action='read', iostat=iostat) 
            IF (iostat .NE. 0) THEN
              PRINT*, 'Error: Can''t open owner file: ', TRIM(meshpath)
              RETURN
            ELSE
              nlines_owner = 0
              DO 
                READ(file_unit_owner, '(a)', iostat=iostat) 
                IF (iostat .NE. 0) THEN
                  REWIND(file_unit_owner) 
                  ALLOCATE(lines_owner(nlines_owner))
! 2. 打开文件（与owner逻辑完全一致）
                  neighbourfilepath = TRIM(meshpath)//'/neighbour'
                  file_unit_neighbour = GET_FREE_UNIT()
                  OPEN(unit=file_unit_neighbour, file=neighbourfilepath&
&                , status='old', action='read', iostat=iostat) 
                  IF (iostat .NE. 0) THEN
! 错误信息与owner格式统
                    PRINT*, 'Error: Can''t open neighbour file: ', TRIM(&
&                   meshpath)
                    RETURN
                  ELSE
                    nlines_neighbour = 0
                    DO 
! 逐行读取计数
                      READ(file_unit_neighbour, '(a)', iostat=iostat) 
                      IF (iostat .NE. 0) THEN
                        REWIND(file_unit_neighbour) 
! 重置文件指针
                        ALLOCATE(lines_neighbour(nlines_neighbour))
! 分配存储所有行的数组
                        facesfilepath = TRIM(meshpath)//'/faces'
                        file_unit_faces = GET_FREE_UNIT()
                        OPEN(unit=file_unit_faces, file=facesfilepath, &
&                      status='old', action='read', iostat=iostat) 
                        IF (iostat .NE. 0) THEN
                          PRINT*, 'Error: Can''t open faces file: ', &
&                         TRIM(meshpath)
!            allocate(faces%faces(0))
                          RETURN
                        ELSE
                          nlines_faces = 0
                          DO 
                            READ(file_unit_faces, '(a)', iostat=iostat) 
                            IF (iostat .NE. 0) THEN
                              REWIND(file_unit_faces) 
                              ALLOCATE(lines_faces(74151))
                              DO i=1,nlines_faces
                                READ(file_unit_faces, '(a)') lines_faces&
&                              (i)
                              END DO
                              CLOSE(file_unit_faces) 
                              CALL OFFILE_FINDNITEMSSS(lines_faces, &
&                                                startline_faces, fcount&
&                                               )
                              ALLOCATE(tmp_faces(fcount))
!       do i = 1, fCount
!      		allocate(tmp_faces(i)%points(4))
!       end do
                              PRINT*, 'ABC'
                              DO i=1,2
                                line = TRIM(lines_faces(startline_faces+&
&                                 i-1))
                                bracketl = INDEX(line, '(')
                                bracketr = INDEX(line, ')')
                                READ(line(1:bracketl-1), *) pt_count
                              END DO
                              ALLOCATE(pts_faces(pt_count), source=&
&                             0_int64)
!		allocate(wing_update(99, 2), source=0.0_real64)
!!!!!!!!!!!!!!
!!!!!!!!!!!!!!Buflow
                              ALLOCATE(owner_tempmesh(0))
                              ALLOCATE(neighbour_tempmesh(0))
                              ALLOCATE(facepoints_tempmesh(0, 0))
                              PRINT*, 'A'
                              ALLOCATE(points_tempmesh(37243, 3))
                              CALL READOPENFOAMMESHH(meshpath, tempmesh)
                              PRINT*, 'ABC'
                              npoints = SIZE(points_tempmesh, 1)
                              nfaces = SIZE(owner_tempmesh)
                              ncells = MAXVAL(owner_tempmesh)
!四种边界
                              nboundaries = SIZE(tempmesh%boundarynames)
!所有边界面的总数
                              nfaceperbdry = SIZE(tempmesh%&
&                               boundarynumfaces)
                              ALLOCATE(currentboundary(nfaceperbdry))
                              ALLOCATE(gradp(ncells, 3))
                              ALLOCATE(sj(ncells))
                              ALLOCATE(sjcount(ncells))
                              ALLOCATE(rj(ncells))
                              ALLOCATE(rjsjf(nfaces, 2), source=0.0_8)
                              ALLOCATE(eps2(nfaces), source=0.0_8)
                              ALLOCATE(eps4(nfaces), source=0.0_8)
                              ALLOCATE(p_matrix(ncells, 1))
                              ALLOCATE(facevals(nfaces, 5))
!		allocate(P_eps(nCells))
                              ALLOCATE(temp_grad(ncells, 1, 3))
!这个是正确写法，错误写法在程序运行完之后会报错。正确写法和错误写法结果一样
                              ALLOCATE(timefluxes(ncells))
                              ALLOCATE(surfaceareas(ncells))
                              ALLOCATE(timefluxess(ncells))
                              ALLOCATE(surfaceareass(ncells))
                              ALLOCATE(facerhot(nfaces, 2), source=0.0_8&
&                             )
                              ALLOCATE(cellrhot(ncells, 2), source=0.0_8&
&                             )
                              ALLOCATE(facevel(3))
                              ALLOCATE(positionn(3))
                              ALLOCATE(fdeltas(nfaces, 5), source=0.0_8)
                              ALLOCATE(fdgrads(ncells, 5, 3))
                              ALLOCATE(eps22(nfaces))
                              ALLOCATE(eps44(nfaces))
                              ALLOCATE(epss(nfaces, 2), source=0.0_8)
                              ALLOCATE(diffusionflux(5))
                              ALLOCATE(unitfa(3))
                              ALLOCATE(fd(5))
                              ALLOCATE(farownerfd(5))
                              ALLOCATE(farneighbourfd(5))
!        allocate(faceVals_dd(nFaces, 5)) 
!        allocate(faceVals_d(nFaces, 5)) 
                              ALLOCATE(fluxresiduals(ncells, 5), source=&
&                             0.0_8)
                              ALLOCATE(dt_val(ncells), source=0.0_8)
!		allocate(first5_refs(5,3))	
                              ALLOCATE(encodeprimitives3dd(ncells, 5))
                              ALLOCATE(initialvalues(5))
! 分配结构体数组
                              ALLOCATE(cellprimitives_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(cellstate_sln(ncells, 5), source=&
&                             0.0d0)
                              ALLOCATE(cellfluxes_sln(ncells, 15), &
&                             source=0.0d0)
                              ALLOCATE(fluxresiduals_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(facefluxes_sln(nfaces, 15), &
&                             source=0.0d0)
                              ALLOCATE(faces_mesh(nfaces, 2))
                              ALLOCATE(favecs_mesh(nfaces, 3))
                              ALLOCATE(fcenters_mesh(nfaces, 3))
                              ALLOCATE(cells_mesh(ncells, 6))
                              ALLOCATE(cvols_mesh(ncells))
                              ALLOCATE(ccenters_mesh(ncells, 3))
                              ALLOCATE(cellsizes_mesh(ncells, 3))
                              ALLOCATE(boundaryfaces_mesh(nboundaries, &
&                             MAXVAL(tempmesh%boundarynumfaces)))
                              ALLOCATE(dt_solve(ncells))
                              ALLOCATE(sol(ncells, 5))
                              ALLOCATE(fcs(6, 3))
                              ALLOCATE(cell_favecs(6, 3))
                              ALLOCATE(cellpts(0, 3))
!        allocate(cellPtss(1,3)) 
                              ALLOCATE(facepts(SIZE(facepoints_tempmesh(&
&                             1, :)), 3))
                              ALLOCATE(cellfacecount(ncells))
                              ALLOCATE(uunitvec(3))
!        allocate(points_tempMesh(size(point_update,1), size(point_update,2))) !在readOFPointsFilef里面已经allocate
                              ALLOCATE(points_meshdefor(37254, 3), &
&                             source=0.0_8)
                              ALLOCATE(inoutput(99, 2))
                              ALLOCATE(wing(99, 2))
                              ALLOCATE(wing_coords(99, 2))
                              ALLOCATE(inoutput_coords(99, 2))
                              ALLOCATE(control_points(198, 2))
                              ALLOCATE(r_row(198))
                              ALLOCATE(phi_row(198))
                              ALLOCATE(mat_inv(198, 198), source=0.0_8)
                              ALLOCATE(distances(198))
                              ALLOCATE(phi(198, 198))
                              ALLOCATE(point_update(npoints, 3))
!!!!!!!!!!!!!!Buflow        
! 读取网格
!		meshPath = "mesh/OFairfoilMesh"	
!		mesh = OpenFOAMMesh(meshPath, point_update)
! 修改后的代码
!		meshInfo = unstructuredMeshInfo(mesh) 
!		nCells = meshInfo(1)  
!		allocate(cellPrimitives(nCells, 5)) 
                              ALLOCATE(cellprimitivesout(18513, 5))
! 显式赋值，确保 Tapenade 识别为"活跃输出"
                              cellprimitivesout = 0.0d0
                              PRINT*, 'ABC'
! 调用网格变形，获取变形后的网格点（point_update）
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                              ALLOCATE(fluxresiduals(ncells, 5), source=&
!&                             0.0_8)
							          ! === adjoint (b) variables allocate ===
        ! 對應 gradP, P_matrix, temp_grad, faceVals
							allocate(gradPd(nCells, 3))
							allocate(p_matrixd(nCells, 1))
							allocate(temp_gradd(nCells, 1, 3))
							allocate(faceValsd(nFaces, 5))

							! 對應 sj, rj, rjsjF
							allocate(sjd(nCells))
							allocate(rjd(nCells))
							allocate(rjsjFd(nFaces, 2))

							! 對應 eps2, eps4
							allocate(eps2d(nFaces))
							allocate(eps4d(nFaces))

							! 對應 eps22, diffusionFlux, unitFA, fD, epss
							allocate(eps22d(nFaces))
							allocate(diffusionFluxd(5))
							allocate(unitFAd(3))
							allocate(fDd(5))
							allocate(epssd(nFaces, 2))

							! 對應 fDeltas, fDGrads
							allocate(fDeltasd(nFaces, 5))
							allocate(fDGradsd(nCells, 5, 3))
							! 對應 cellState_sln, cellFluxes_sln, cellPrimitives_sln,
							!       fluxResiduals_sln, faceFluxes_sln
							allocate(cellState_slnd(nCells, 5))
							allocate(cellFluxes_slnd(nCells, 15))
							allocate(cellPrimitives_slnd(nCells, 5))
							allocate(fluxResiduals_slnd(nCells, 5))
							allocate(faceFluxes_slnd(nFaces, 15))

							! 對應 cVols_mesh, cCenters_mesh, fAVecs_mesh, fCenters_mesh
							allocate(cVols_meshd(nCells))
							allocate(cCenters_meshd(nCells, 3))
							allocate(fAVecs_meshd(nFaces, 3))
							allocate(fCenters_meshd(nFaces, 3))

							! 對應 facePts, fCs, cell_fAVecs
							allocate(facePtsd(size(facePoints_tempMesh(1, :)), 3))
							allocate(fCsd(6, 3))
							allocate(cell_fAVecsd(6, 3))

							! 對應 UunitVec, points_tempMesh, point_update
							allocate(uunitVecd(3))
							allocate(points_tempMeshd(37243, 3))
							allocate(point_updated(nPoints, 3))

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!							allocate(cellPrimitivesoutd(18513, 5), source=1.0_8)
!							data_4D137d(1,1:4) = 1.0d0
							allocate(fluxResidualsd(nCells, 5), source=0.0_8)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                              CALL AIRFOIL_DEFORMATION_HH(data_4d137)
                              PRINT*, 'ABC'
! 调用CFD计算，传入变形网格点，输出结果到cellPrimitives
                              CALL COMPUTE_CFD(cellprimitivesout)
                              ! 固定收敛解 w，对 data_4d137(1,1) 作 (R(a+eps)-R(a))/eps，写 VTK；可与 AD 的 -b 对照
                              !通过差分稳态计算残差对变形参数的偏导
                              !CALL RESIDUAL_FD_DEFORM_PARAM_VTK(data_4d137, cellprimitivesout, &
!&   meshpath, iparam_col=1, eps_fd=1.0d-5, vtk_stem='residual_fd_x1')
							  ncells = 18513
								n = ncells*5
								ALLOCATE(b_i(n), x_tan(n), dwdx(n, 5), rhs_rho(ncells, 5))
								tol = 1.0d-8!tol = 1.0d-8
								maxiter = 10
								m_restart = 50!80,提高能提高收敛速度（试过提高200，过多会增加内存负担，影响运行速度。没验证过过高是否反而下降）
								! ===== 新增：建預條件（只需一次（或每个网格/基底一次））
								pc_outer_counter = 0_8
								CALL BUILD_PC_JST_L1(data_4d137, cellprimitivesout)   ! 先建一次，保证本轮开着
								use_tangent_ptc_outer = .TRUE.
								ptc_steps = 3_8
								ptc_sigma0 = 0.80d0
								ptc_sigma_decay = 0.35d0
								ptc_tol_start = 5.0d-4
								ptc_omega_stage = 0.75d0

								DO i_param = 1, 1
								!DO i_param = 1, 4
								  !计算∂R/∂w *dw/dx=-∂R/∂x的-∂R/∂x
								  CALL TANGENT_RHS_I(data_4d137, cellprimitivesout, n, i_param, b_i)
								  !准确来说这不应该是压力残差，应该取得是守恒变量第一维度密度的残差
								  pc_outer_counter = pc_outer_counter + 1_8
								  DO c = 1, ncells
								  ! 只取每个单元的 P 分量
									  rhs_rho(c, i_param) = b_i((c-1)*5 + 1)   
								  END DO
								  ! 第二個開始用前一個 x_tan 作初值,可以加速收敛
								  x_tan = 0.0_8
								  IF (use_tangent_ptc_outer) THEN
									ALLOCATE(ptc_res(n), ptc_dx(n), ptc_ax(n))
									ptc_res = b_i
									ptc_sigma = ptc_sigma0
									ptc_tol_stage = MAX(tol, ptc_tol_start)
									ptc_res_prev = SQRT(SUM(ptc_res*ptc_res))
									bnrm_i = MAX(1.0d-30, SQRT(SUM(b_i*b_i)))

									DO ptc_it = 1_8, ptc_steps
									  CALL BUILD_PC_JST_L1(data_4d137, cellprimitivesout)
									  pc_use_ptc_shift = .TRUE.
									  pc_ptc_alpha = MIN(pc_ptc_alpha_max, MAX(pc_ptc_alpha_min, ptc_sigma))
									  maxiter_stage = MAX(3_8, maxiter-1_8)
									  ptc_dx = 0.0_8
									  CALL SOLVE_TANGENT_JFGMRES(data_4d137, cellprimitivesout, n, ptc_res, ptc_dx, &
									& ptc_tol_stage, maxiter_stage, m_restart, info_stage)
									  x_tan = x_tan + ptc_omega_stage * ptc_dx

									  CALL TANGENT_MATVEC(data_4d137, cellprimitivesout, n, x_tan, ptc_ax)
									  ptc_res = b_i - ptc_ax
									  ptc_res_new = SQRT(SUM(ptc_res*ptc_res))
									  PRINT *, '[PTC-OUTER] param=', i_param, ' it=', ptc_it, ' sigma=', ptc_sigma, &
									& ' tol_lin=', ptc_tol_stage, ' ||r||/||b||=', ptc_res_new/bnrm_i, ' info=', info_stage
									  IF (ptc_res_new <= tol * bnrm_i) EXIT
									  IF (ptc_res_new > 0.95d0 * ptc_res_prev) THEN
										ptc_omega_stage = MAX(0.35d0, 0.80d0*ptc_omega_stage)
									  ELSE
										ptc_omega_stage = MIN(0.90d0, 1.05d0*ptc_omega_stage)
									  END IF
									  ptc_res_prev = ptc_res_new
									  ptc_sigma = MAX(0.05d0, ptc_sigma * ptc_sigma_decay)
									  ptc_tol_stage = MAX(tol, ptc_tol_stage * 0.20d0)
									END DO

									! final polish on original system (sigma=0)
									pc_use_ptc_shift = .FALSE.
									CALL BUILD_PC_JST_L1(data_4d137, cellprimitivesout)
									CALL SOLVE_TANGENT_JFGMRES(data_4d137, cellprimitivesout, n, b_i, x_tan, tol, maxiter, m_restart, info)
									DEALLOCATE(ptc_res, ptc_dx, ptc_ax)
								  ELSE
									!无雅可比矩阵GMRES方法(正向自动微分求解矩阵向量积)求解dw/dx
									CALL SOLVE_TANGENT_JFGMRES(data_4d137, cellprimitivesout, n, b_i, x_tan, tol, maxiter, m_restart, info)
								  END IF
								  !x_tan表示的是一个变形参数的dw/dx,维度为（ncells*5）,dwdx表示的是四个变形参数的dw/dx，维度为（ncells*5，4）
								  dwdx(1:n, i_param) = x_tan
								  PRINT *, 'Tangent param ', i_param, ' GMRES info=', info
								END DO
								!对mach的梯度
							    machnum = 273.00_8 / SQRT(1.4_8*287.05_8*300.0_8)
							    !计算∂R/∂w *dw/dx=-∂R/∂x的-∂R/∂x,这里的x为mach
							    !b_i=-∂R/∂MACH
							    !CALL TANGENT_RHS_MACH(data_4d137, cellprimitivesout, machnum, n, b_i)
							    !CALL RHS_MACH_VERIFY(data_4d137, cellprimitivesout, machnum, n, b_i)
							    !STOP 'RHS_MACH_VERIFY done.'
							    !rhs_rho(1:ncells, 5) = b_i(1:ncells)
   								!x_tan = 0.0_8
   								!无雅可比矩阵GMRES方法(正向自动微分求解矩阵向量积)求解dw/dx
   								!CALL SOLVE_TANGENT_JFGMRES(data_4d137, cellprimitivesout, n, b_i, x_tan, tol, maxiter, m_restart, info)
    							dwdx(1:n, 5) = 0.0_8
								rhs_rho(1:ncells, 5) = 0.0_8!这里实际上是对mach的导数
    							PRINT *, 'Tangent param (Mach) GMRES info=', info
    							!输出vtk,csv
								meshpath = 'mesh/OFairfoilMesh'
								CALL OUTPUT_WALL_CP_CSV(meshpath, point_update, cellprimitivesout, dwdx, ncells, 'wall_cp_data.csv')
								print *, "ABD"
								CALL COMPUTE_STEADY_RESIDUAL(data_4d137, cellprimitivesout)
								CALL OUTPUTVTK_D(meshpath, cellprimitivesout, dwdx, 'solution_001', &
& point_update, rhs_rho=rhs_rho, residual_rho=fluxresiduals_sln(1:ncells, 1))
								print *, "ABD"
								DEALLOCATE(b_i, x_tan, dwdx, rhs_rho)
! 释放point_update内存        
!!!!!!!!!!!!meshdeformation                                 DEALLOCATE(cellprimitivesout)

							  deallocate(fluxResidualsd, fluxResiduals_slnd, &
									   cVols_meshd, faceFluxes_slnd, fAVecs_meshd)

							  deallocate(eps22d, fDd, unitFAd, diffusionFluxd, fDeltasd, epssd, &
									   cellFluxes_slnd)

							  deallocate(cellPrimitives_slnd, cellState_slnd, facePtsd, fCsd, &
									   cell_fAVecsd, points_tempMeshd, point_updated)

							  deallocate(eps4d, eps2d, rjsjFd, p_matrixd, gradPd, temp_gradd, &
									   cCenters_meshd, sjd, rjd, fDGradsd, uunitVecd, &
									   faceValsd, fCenters_meshd)
                              DEALLOCATE(lines_defor)
                              IF (ALLOCATED(inoutput)) THEN
                                DEALLOCATE(inoutput)
                              END IF
                              IF (ALLOCATED(wing)) THEN
                                DEALLOCATE(wing)
                              END IF
                              IF (ALLOCATED(point_update)) THEN
                                DEALLOCATE(point_update)
                              END IF
                              IF (ALLOCATED(points_meshdefor)) THEN
                                DEALLOCATE(points_meshdefor)
                              END IF
                              IF (ALLOCATED(mat_inv)) THEN
                                DEALLOCATE(mat_inv)
                              END IF
                              IF (ALLOCATED(wing_coords)) THEN
                                DEALLOCATE(wing_coords)
                              END IF
                              IF (ALLOCATED(inoutput_coords)) THEN
                                DEALLOCATE(inoutput_coords)
                              END IF
                              IF (ALLOCATED(r_row)) THEN
                                DEALLOCATE(r_row)
                              END IF
                              IF (ALLOCATED(phi_row)) THEN
                                DEALLOCATE(phi_row)
                              END IF
                              IF (ALLOCATED(control_points)) THEN
                                DEALLOCATE(control_points)
                              END IF
                              IF (ALLOCATED(phi)) THEN
                                DEALLOCATE(phi)
                              END IF
                              IF (ALLOCATED(distances)) THEN
                                DEALLOCATE(distances)
                              END IF
!		if (allocated(wing_update)) deallocate(wing_update)
!!!!!!!!!!!! meshdeformation
!!!!!!!!!!!! Buflow
                              DEALLOCATE(currentboundary)
!        deallocate(P_eps)
                              DEALLOCATE(p_matrix)
                              DEALLOCATE(temp_grad)
                              DEALLOCATE(gradp)
                              DEALLOCATE(sj)
                              DEALLOCATE(sjcount)
                              DEALLOCATE(rj)
                              DEALLOCATE(rjsjf)
                              DEALLOCATE(eps2)
                              DEALLOCATE(eps4)
                              DEALLOCATE(facevals)
                              DEALLOCATE(timefluxes)
                              DEALLOCATE(surfaceareas)
                              DEALLOCATE(timefluxess)
                              DEALLOCATE(surfaceareass)
                              DEALLOCATE(facevel)
                              DEALLOCATE(positionn)
                              DEALLOCATE(facerhot)
                              DEALLOCATE(cellrhot)
                              DEALLOCATE(epss)
                              DEALLOCATE(fdeltas)
                              DEALLOCATE(fdgrads)
                              DEALLOCATE(eps22)
                              DEALLOCATE(eps44)
                              DEALLOCATE(diffusionflux)
                              DEALLOCATE(unitfa)
                              DEALLOCATE(fd)
                              DEALLOCATE(farownerfd)
                              DEALLOCATE(farneighbourfd)
!		deallocate(faceVals_dd)
!		deallocate(faceVals_d)
                              DEALLOCATE(fluxresiduals)
                              DEALLOCATE(dt_val)
                              PRINT*, 'Aa'
                              DEALLOCATE(blines)
                              PRINT*, 'c'
!		if (allocated(lines_neighbour)) deallocate(lines_neighbour)
!     	deallocate()
                              PRINT*, 'c'
                              DEALLOCATE(lines_owner)
                              PRINT*, 'Aa'
                              DEALLOCATE(lines_faces)
                              DEALLOCATE(pts_faces)
                              DEALLOCATE(tmp_faces)
                              DEALLOCATE(dt_solve)
!		deallocate(first5_refs(5,3))
                              DEALLOCATE(fcs)
                              DEALLOCATE(cell_favecs)
                              DEALLOCATE(cellpts)
                              DEALLOCATE(cellfacecount)
                              DEALLOCATE(facepts)
                              DEALLOCATE(uunitvec)
                              DEALLOCATE(boundarynumfacess)
! 以下為 main 中 allocate 但此前未 deallocate 的變量（避免 main_AD 重複分配報錯）
                              IF (ALLOCATED(owner_tempmesh)) THEN
                                DEALLOCATE(owner_tempmesh)
                              END IF
                              IF (ALLOCATED(neighbour_tempmesh)) THEN
                                DEALLOCATE(neighbour_tempmesh)
                              END IF
                              IF (ALLOCATED(facepoints_tempmesh)) THEN
                                DEALLOCATE(facepoints_tempmesh)
                              END IF
                              IF (ALLOCATED(points_tempmesh)) THEN
                                DEALLOCATE(points_tempmesh)
                              END IF
                              IF (ALLOCATED(boundarystartfacess)) THEN
                                DEALLOCATE(boundarystartfacess)
                              END IF
                              IF (ALLOCATED(encodeprimitives3dd)) THEN
                                DEALLOCATE(encodeprimitives3dd)
                              END IF
                              IF (ALLOCATED(initialvalues)) THEN
                                DEALLOCATE(initialvalues)
                              END IF
                              IF (ALLOCATED(cellprimitives_sln)) THEN
                                DEALLOCATE(cellprimitives_sln)
                              END IF
                              IF (ALLOCATED(cellstate_sln)) THEN
                                DEALLOCATE(cellstate_sln)
                              END IF
                              IF (ALLOCATED(cellfluxes_sln)) THEN
                                DEALLOCATE(cellfluxes_sln)
                              END IF
                              IF (ALLOCATED(fluxresiduals_sln)) THEN
                                DEALLOCATE(fluxresiduals_sln)
                              END IF
                              IF (ALLOCATED(facefluxes_sln)) THEN
                                DEALLOCATE(facefluxes_sln)
                              END IF
                              IF (ALLOCATED(faces_mesh)) THEN
                                DEALLOCATE(faces_mesh)
                              END IF
                              IF (ALLOCATED(favecs_mesh)) THEN
                                DEALLOCATE(favecs_mesh)
                              END IF
                              IF (ALLOCATED(fcenters_mesh)) THEN
                                DEALLOCATE(fcenters_mesh)
                              END IF
                              IF (ALLOCATED(cells_mesh)) THEN
                                DEALLOCATE(cells_mesh)
                              END IF
                              IF (ALLOCATED(cvols_mesh)) THEN
                                DEALLOCATE(cvols_mesh)
                              END IF
                              IF (ALLOCATED(ccenters_mesh)) THEN
                                DEALLOCATE(ccenters_mesh)
                              END IF
                              IF (ALLOCATED(cellsizes_mesh)) THEN
                                DEALLOCATE(cellsizes_mesh)
                              END IF
                              IF (ALLOCATED(boundaryfaces_mesh)) THEN
                                DEALLOCATE(boundaryfaces_mesh)
                              END IF
                              IF (ALLOCATED(sol)) THEN
                                DEALLOCATE(sol)
                              END IF
                              PRINT*, 'Aa'
!!!!!!!!!!!! Buflow		
                              GOTO 100
                            ELSE
                              nlines_faces = nlines_faces + 1
                            END IF
                          END DO
                        END IF
                      ELSE
                        nlines_neighbour = nlines_neighbour + 1
                      END IF
                    END DO
                  END IF
                ELSE
                  nlines_owner = nlines_owner + 1
                END IF
              END DO
            END IF
          ELSE
            nlines_boundary = nlines_boundary + 1
          END IF
        END DO
      ELSE
        nlines_points = nlines_points + 1
      END IF
    END DO
 100 CONTINUE
  END SUBROUTINE MAIN

! =========================================================================
! main_AD：复制 main 的 allocate/deallocate，仅调用 compute_steady_residual
! 供 Tapenade 微分时生成微分变量的存储，避免 SIGSEGV
! 输入：data_4D137(4个变形参数), cellPrimitives(稳态流场，需预先从 main 得到)
! 输出：fluxResidualsOut(残差)
! Tapenade 入口改为 main_AD 而非 compute_steady_residual
! =========================================================================
  SUBROUTINE MAIN_AD(data_4d137, cellprimitives)
    USE TYPESMODULE_DIFF
    IMPLICIT NONE
    REAL(kind=8), INTENT(IN) :: data_4d137(1, 4)
    REAL(kind=8), INTENT(IN) :: cellprimitives(:, :)
!        real(kind=8), allocatable, intent(out) :: fluxResidualsOut(:,:)
    INTEGER(kind=8) :: ncells, meshinfo(4), iostat, nlines_points, &
&   file_unit_points, nfaces, nfaceperbdry, nboundaries, nlines_boundary&
&   , file_unit_boundary, nlines_owner, file_unit_owner, &
&   nlines_neighbour, file_unit_neighbour, nlines_faces, file_unit_faces&
&   , startline_faces, fcount, i, bracketl, bracketr, pt_count
    INTEGER(kind=8) :: bcount, startline_boundary, npoints
    CHARACTER(len=256) :: meshpath, pointsfilepath, boundaryfilepath, &
&   ownerfilepath, neighbourfilepath, facesfilepath, line
    TYPE(MESHDATA) :: tempmesh
    INTRINSIC TRIM
    INTRINSIC INDEX
    INTRINSIC SIZE
    INTRINSIC MAXVAL
    INTRINSIC ALLOCATED
    meshpath = 'mesh/OFairfoilMesh'
    file_unit_points = GET_FREE_UNITT()
    pointsfilepath = TRIM(meshpath)//'/points'
    OPEN(unit=file_unit_points, file=pointsfilepath, status='old', &
&  action='read', iostat=iostat) 
    nlines_points = 0
    DO 
      READ(file_unit_points, '(a)', iostat=iostat) 
      IF (iostat .NE. 0) THEN
        REWIND(file_unit_points) 
        ALLOCATE(lines_defor(nlines_points))
        boundaryfilepath = TRIM(meshpath)//'/boundary'
        file_unit_boundary = GET_FREE_UNIT()
        OPEN(unit=file_unit_boundary, file=boundaryfilepath, status=&
&      'old', action='read', iostat=iostat) 
        nlines_boundary = 0
        DO 
          READ(file_unit_boundary, '(a)', iostat=iostat) 
          IF (iostat .NE. 0) THEN
            REWIND(file_unit_boundary) 
            ALLOCATE(blines(nlines_boundary))
            DO i=1,nlines_boundary
              READ(file_unit_boundary, '(a)') blines(i)
            END DO
            CLOSE(file_unit_boundary) 
            CALL OFFILE_FINDNITEMSSS(blines, startline_boundary, bcount)
            ALLOCATE(boundarynumfacess(bcount))
            ALLOCATE(boundarystartfacess(bcount))
            ownerfilepath = TRIM(meshpath)//'/owner'
            file_unit_owner = GET_FREE_UNIT()
            OPEN(unit=file_unit_owner, file=ownerfilepath, status='old'&
&          , action='read', iostat=iostat) 
            IF (iostat .NE. 0) THEN
              PRINT*, 'Error: Can''t open owner file: ', TRIM(meshpath)
              RETURN
            ELSE
              nlines_owner = 0
              DO 
                READ(file_unit_owner, '(a)', iostat=iostat) 
                IF (iostat .NE. 0) THEN
                  REWIND(file_unit_owner) 
                  ALLOCATE(lines_owner(nlines_owner))
                  neighbourfilepath = TRIM(meshpath)//'/neighbour'
                  file_unit_neighbour = GET_FREE_UNIT()
                  OPEN(unit=file_unit_neighbour, file=neighbourfilepath&
&                , status='old', action='read', iostat=iostat) 
                  IF (iostat .NE. 0) THEN
                    PRINT*, 'Error: Can''t open neighbour file: ', TRIM(&
&                   meshpath)
                    RETURN
                  ELSE
                    nlines_neighbour = 0
                    DO 
                      READ(file_unit_neighbour, '(a)', iostat=iostat) 
                      IF (iostat .NE. 0) THEN
                        REWIND(file_unit_neighbour) 
!        allocate(lines_neighbour(nLines_neighbour))
                        facesfilepath = TRIM(meshpath)//'/faces'
                        file_unit_faces = GET_FREE_UNIT()
                        OPEN(unit=file_unit_faces, file=facesfilepath, &
&                      status='old', action='read', iostat=iostat) 
                        IF (iostat .NE. 0) THEN
                          PRINT*, 'Error: Can''t open faces file: ', &
&                         TRIM(meshpath)
                          RETURN
                        ELSE
                          nlines_faces = 0
                          DO 
                            READ(file_unit_faces, '(a)', iostat=iostat) 
                            IF (iostat .NE. 0) THEN
                              REWIND(file_unit_faces) 
                              ALLOCATE(lines_faces(74151))
                              DO i=1,nlines_faces
                                READ(file_unit_faces, '(a)') lines_faces&
&                              (i)
                              END DO
                              CLOSE(file_unit_faces) 
                              CALL OFFILE_FINDNITEMSSS(lines_faces, &
&                                                startline_faces, fcount&
&                                               )
                              ALLOCATE(tmp_faces(fcount))
                              DO i=1,2
                                line = TRIM(lines_faces(startline_faces+&
&                                 i-1))
                                bracketl = INDEX(line, '(')
                                bracketr = INDEX(line, ')')
                                READ(line(1:bracketl-1), *) pt_count
                              END DO
                              ALLOCATE(pts_faces(pt_count), source=&
&                             0_int64)
                              ALLOCATE(owner_tempmesh(0))
                              ALLOCATE(neighbour_tempmesh(0))
                              ALLOCATE(facepoints_tempmesh(0, 0))
                              ALLOCATE(points_tempmesh(37243, 3))
                              CALL READOPENFOAMMESHH(meshpath, tempmesh)
                              npoints = SIZE(points_tempmesh, 1)
                              nfaces = SIZE(owner_tempmesh)
                              ncells = MAXVAL(owner_tempmesh)
                              nboundaries = SIZE(tempmesh%boundarynames)
                              nfaceperbdry = SIZE(tempmesh%&
&                               boundarynumfaces)
                              ALLOCATE(currentboundary(nfaceperbdry))
                              ALLOCATE(gradp(ncells, 3))
                              ALLOCATE(sj(ncells))
                              ALLOCATE(sjcount(ncells))
                              ALLOCATE(rj(ncells))
                              ALLOCATE(rjsjf(nfaces, 2), source=0.0_8)
                              ALLOCATE(eps2(nfaces), source=0.0_8)
                              ALLOCATE(eps4(nfaces), source=0.0_8)
                              ALLOCATE(p_matrix(ncells, 1))
                              ALLOCATE(facevals(nfaces, 5))
                              ALLOCATE(temp_grad(ncells, 1, 3))
                              ALLOCATE(timefluxes(ncells))
                              ALLOCATE(surfaceareas(ncells))
                              ALLOCATE(timefluxess(ncells))
                              ALLOCATE(surfaceareass(ncells))
                              ALLOCATE(facerhot(nfaces, 2), source=0.0_8&
&                             )
                              ALLOCATE(cellrhot(ncells, 2), source=0.0_8&
&                             )
                              ALLOCATE(facevel(3))
                              ALLOCATE(positionn(3))
                              ALLOCATE(fdeltas(nfaces, 5), source=0.0_8)
                              ALLOCATE(fdgrads(ncells, 5, 3))
                              ALLOCATE(eps22(nfaces))
                              ALLOCATE(eps44(nfaces))
                              ALLOCATE(epss(nfaces, 2), source=0.0_8)
                              ALLOCATE(diffusionflux(5))
                              ALLOCATE(unitfa(3))
                              ALLOCATE(fd(5))
                              ALLOCATE(farownerfd(5))
                              ALLOCATE(farneighbourfd(5))
!        allocate(faceVals_dd(nFaces, 5))
!        allocate(faceVals_d(nFaces, 5))
                              ALLOCATE(fluxresiduals(ncells, 5), source=&
&                             0.0_8)
                              ALLOCATE(dt_val(ncells), source=0.0_8)
                              ALLOCATE(encodeprimitives3dd(ncells, 5))
                              ALLOCATE(initialvalues(5))
                              ALLOCATE(cellprimitives_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(cellstate_sln(ncells, 5), source=&
&                             0.0d0)
                              ALLOCATE(cellfluxes_sln(ncells, 15), &
&                             source=0.0d0)
                              ALLOCATE(fluxresiduals_sln(ncells, 5), &
&                             source=0.0d0)
                              ALLOCATE(facefluxes_sln(nfaces, 15), &
&                             source=0.0d0)
                              ALLOCATE(faces_mesh(nfaces, 2))
                              ALLOCATE(favecs_mesh(nfaces, 3))
                              ALLOCATE(fcenters_mesh(nfaces, 3))
                              ALLOCATE(cells_mesh(ncells, 6))
                              ALLOCATE(cvols_mesh(ncells))
                              ALLOCATE(ccenters_mesh(ncells, 3))
                              ALLOCATE(cellsizes_mesh(ncells, 3))
                              ALLOCATE(boundaryfaces_mesh(nboundaries, &
&                             MAXVAL(tempmesh%boundarynumfaces)))
                              ALLOCATE(dt_solve(ncells))
                              ALLOCATE(sol(ncells, 5))
                              ALLOCATE(fcs(6, 3))
                              ALLOCATE(cell_favecs(6, 3))
                              ALLOCATE(cellpts(0, 3))
                              ALLOCATE(facepts(SIZE(facepoints_tempmesh(&
&                             1, :)), 3))
                              ALLOCATE(cellfacecount(ncells))
                              ALLOCATE(uunitvec(3))
                              ALLOCATE(points_meshdefor(37254, 3), &
&                             source=0.0_8)
                              ALLOCATE(inoutput(99, 2))
                              ALLOCATE(wing(99, 2))
                              ALLOCATE(wing_coords(99, 2))
                              ALLOCATE(inoutput_coords(99, 2))
                              ALLOCATE(control_points(198, 2))
                              ALLOCATE(r_row(198))
                              ALLOCATE(phi_row(198))
                              ALLOCATE(mat_inv(198, 198), source=0.0_8)
                              ALLOCATE(distances(198))
                              ALLOCATE(phi(198, 198))
                              ALLOCATE(point_update(npoints, 3))
                              CALL AIRFOIL_DEFORMATION_HH(data_4d137)
!        allocate(fluxResidualsOut(nCells, 5), source=0.0_8)
!!!!!!!!!!!!!!!!!!
                              CALL COMPUTE_STEADY_RESIDUAL(data_4d137, &
&                                                    cellprimitives)
!!!!!!!!!!!!!!!!!!
                              DEALLOCATE(lines_defor)
                              IF (ALLOCATED(inoutput)) THEN
                                DEALLOCATE(inoutput)
                              END IF
                              IF (ALLOCATED(wing)) THEN
                                DEALLOCATE(wing)
                              END IF
                              IF (ALLOCATED(point_update)) THEN
                                DEALLOCATE(point_update)
                              END IF
                              IF (ALLOCATED(points_meshdefor)) THEN
                                DEALLOCATE(points_meshdefor)
                              END IF
                              IF (ALLOCATED(mat_inv)) THEN
                                DEALLOCATE(mat_inv)
                              END IF
                              IF (ALLOCATED(wing_coords)) THEN
                                DEALLOCATE(wing_coords)
                              END IF
                              IF (ALLOCATED(inoutput_coords)) THEN
                                DEALLOCATE(inoutput_coords)
                              END IF
                              IF (ALLOCATED(r_row)) THEN
                                DEALLOCATE(r_row)
                              END IF
                              IF (ALLOCATED(phi_row)) THEN
                                DEALLOCATE(phi_row)
                              END IF
                              IF (ALLOCATED(control_points)) THEN
                                DEALLOCATE(control_points)
                              END IF
                              IF (ALLOCATED(phi)) THEN
                                DEALLOCATE(phi)
                              END IF
                              IF (ALLOCATED(distances)) THEN
                                DEALLOCATE(distances)
                              END IF
                              DEALLOCATE(currentboundary)
                              DEALLOCATE(p_matrix)
                              DEALLOCATE(temp_grad)
                              DEALLOCATE(gradp)
                              DEALLOCATE(sj)
                              DEALLOCATE(sjcount)
                              DEALLOCATE(rj)
                              DEALLOCATE(rjsjf)
                              DEALLOCATE(eps2)
                              DEALLOCATE(eps4)
                              DEALLOCATE(facevals)
                              DEALLOCATE(timefluxes)
                              DEALLOCATE(surfaceareas)
                              DEALLOCATE(timefluxess)
                              DEALLOCATE(surfaceareass)
                              DEALLOCATE(facevel)
                              DEALLOCATE(positionn)
                              DEALLOCATE(facerhot)
                              DEALLOCATE(cellrhot)
                              DEALLOCATE(epss)
                              DEALLOCATE(fdeltas)
                              DEALLOCATE(fdgrads)
                              DEALLOCATE(eps22)
                              DEALLOCATE(eps44)
                              DEALLOCATE(diffusionflux)
                              DEALLOCATE(unitfa)
                              DEALLOCATE(fd)
                              DEALLOCATE(farownerfd)
                              DEALLOCATE(farneighbourfd)
!        deallocate(faceVals_dd)
!        deallocate(faceVals_d)
                              DEALLOCATE(fluxresiduals)
                              DEALLOCATE(dt_val)
                              DEALLOCATE(blines)
                              DEALLOCATE(lines_owner)
                              DEALLOCATE(lines_faces)
                              DEALLOCATE(pts_faces)
                              DEALLOCATE(tmp_faces)
                              DEALLOCATE(dt_solve)
                              DEALLOCATE(fcs)
                              DEALLOCATE(cell_favecs)
                              DEALLOCATE(cellpts)
                              DEALLOCATE(cellfacecount)
                              DEALLOCATE(facepts)
                              DEALLOCATE(uunitvec)
                              GOTO 100
                            ELSE
                              nlines_faces = nlines_faces + 1
                            END IF
                          END DO
                        END IF
                      ELSE
                        nlines_neighbour = nlines_neighbour + 1
                      END IF
                    END DO
                  END IF
                ELSE
                  nlines_owner = nlines_owner + 1
                END IF
              END DO
            END IF
          ELSE
            nlines_boundary = nlines_boundary + 1
          END IF
        END DO
      ELSE
        nlines_points = nlines_points + 1
      END IF
    END DO
 100 CONTINUE
  END SUBROUTINE MAIN_AD

  SUBROUTINE READOPENFOAMMESHH(polymeshpath, tempmesh)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: polymeshpath
    TYPE(MESHDATA), INTENT(OUT) :: tempmesh
    CHARACTER(len=256) :: pointsfilepath, facesfilepath, ownerfilepath, &
&   neighbourfilepath, boundaryfilepath
    INTRINSIC TRIM
    pointsfilepath = TRIM(polymeshpath)//'/points'
    facesfilepath = TRIM(polymeshpath)//'/faces'
    ownerfilepath = TRIM(polymeshpath)//'/owner'
    neighbourfilepath = TRIM(polymeshpath)//'/neighbour'
    boundaryfilepath = TRIM(polymeshpath)//'/boundary'
    CALL READOFPOINTSFILE(pointsfilepath)
    facepoints_tempmesh = READOFFACESFILE(facesfilepath)
    owner_tempmesh = READOFOWNERFILE(ownerfilepath)
    neighbour_tempmesh = READOFNEIGHBOURFILE(neighbourfilepath)
    CALL READOFBOUNDARYFILE(boundaryfilepath, tempmesh%boundarynames, &
&                     tempmesh%boundarynumfaces, tempmesh%&
&                     boundarystartfaces)
  END SUBROUTINE READOPENFOAMMESHH

  SUBROUTINE OFFILE_FINDNITEMSSS(filelines, startline, itemcount)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: filelines(:)
    INTEGER(kind=8), INTENT(OUT) :: startline, itemcount
    INTEGER(kind=8) :: i, pos, iostat
    CHARACTER(len=256) :: line
    INTRINSIC SIZE
    INTRINSIC TRIM
    INTRINSIC INDEX
    itemcount = 0
    startline = 0
    DO i=1,SIZE(filelines)
      line = TRIM(filelines(i))
      pos = INDEX(line, 'nPoints') + INDEX(line, 'nFaces') + INDEX(line&
&       , 'size')
      IF (pos .NE. 0) THEN
        READ(line(pos:), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (ISNUMBERRR(TRIM(filelines(i)))) THEN
        READ(filelines(i), *, iostat=iostat) itemcount
        IF (itemcount .GT. 0) THEN
          startline = i + 2
          RETURN
        END IF
      END IF
    END DO
    DO i=1,SIZE(filelines)
      IF (INDEX(filelines(i), '(') .GT. 0) THEN
        startline = i + 1
        GOTO 100
      END IF
    END DO
 100 itemcount = 0
    DO i=startline,SIZE(filelines)
      IF (INDEX(filelines(i), ')') .GT. 0) THEN
        GOTO 110
      ELSE
        itemcount = itemcount + 1
      END IF
    END DO
 110 CONTINUE
  END SUBROUTINE OFFILE_FINDNITEMSSS

  LOGICAL FUNCTION ISNUMBERRR(str)
    IMPLICIT NONE
    CHARACTER(len=*), INTENT(IN) :: str
    REAL(kind=8) :: num
    INTEGER(kind=8) :: iostat
    isnumberrr = .false.
    READ(str, *, iostat=iostat) num
    IF (iostat .EQ. 0) isnumberrr = .true.
  END FUNCTION ISNUMBERRR

END MODULE MAIN_MODULE_DIFF

