!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
! 主程序：通过use模块获取main的显式接口
program RUN_MAIN_NODIFF
! 关键：使用包含main的模块，自动获取显式接口
  USE MAIN_MODULE_DIFF
  USE TYPESMODULE_DIFF, ONLY: mesh_path_runtime, deformation_mode_runtime, &
& deformation_mode_airfoil, deformation_mode_cylinder, &
& cylinder_axis_ratio_runtime, use_petsc_tangent_solver_runtime
  IMPLICIT NONE
! 输入参数
  REAL(kind=8) :: data_4d137(1, 4)
!    !$AD INPUT  ! 标记为微分的输入变量（自变量）
  REAL(kind=8), ALLOCATABLE :: cellprimitivesout(:, :)
  CHARACTER(len=*), PARAMETER :: mesh_case = 'mesh1'
  CHARACTER(len=*), PARAMETER :: deformation_case = 'cylinder'
  CHARACTER(len=*), PARAMETER :: tangent_solver_case = 'petsc'   ! 'native' / 'petsc'
  INTRINSIC ALLOCATED
  INTRINSIC SIZE
!    real(kind=8), allocatable :: fluxResidualsOut(:,:)
! ============================================================
! 一键切换模板：
! 1) mesh_case 可选：'mesh' / 'mesh1'
! 2) deformation_case 可选：'airfoil' / 'cylinder'
! 3) tangent_solver_case 可选：'native' / 'petsc'
! ============================================================
  IF (mesh_case .EQ. 'mesh') THEN
    mesh_path_runtime = 'mesh/OFairfoilMesh'
  ELSE IF (mesh_case .EQ. 'mesh1') THEN
    mesh_path_runtime = 'mesh1/OFairfoilMesh'
  ELSE
    PRINT *, 'Error: unsupported mesh_case = ', mesh_case
    STOP
  END IF
  IF (deformation_case .EQ. 'airfoil') THEN
    deformation_mode_runtime = deformation_mode_airfoil
  ELSE IF (deformation_case .EQ. 'cylinder') THEN
    deformation_mode_runtime = deformation_mode_cylinder
  ELSE
    PRINT *, 'Error: unsupported deformation_case = ', deformation_case
    STOP
  END IF
  IF (tangent_solver_case .EQ. 'native') THEN
    use_petsc_tangent_solver_runtime = .FALSE.
  ELSE IF (tangent_solver_case .EQ. 'petsc') THEN
    use_petsc_tangent_solver_runtime = .TRUE.
  ELSE
    PRINT *, 'Error: unsupported tangent_solver_case = ', tangent_solver_case
    STOP
  END IF
! 圆柱模式参数（长短轴比）
  cylinder_axis_ratio_runtime = 1.15d0
  data_4d137 = 0.0d0
  IF (deformation_mode_runtime .EQ. deformation_mode_airfoil) THEN
! 翼型模式：沿用原四个参数
    data_4d137(1, 1) = -0.75d0
    data_4d137(1, 2) = 0.485d0
    data_4d137(1, 3) = -0.588d0
    data_4d137(1, 4) = -0.912d0
  ELSE
! 圆柱模式：只使用 data_4d137(1,1)
    data_4d137(1, 1) = cylinder_axis_ratio_runtime
  END IF
! 调用main子程序（此时编译器已知晓其接口，支持可分配数组参数）
  CALL MAIN(data_4d137, cellprimitivesout)
  IF (ALLOCATED(cellprimitivesout)) THEN
    PRINT*, 'CFD计算完成，结果维度：', SIZE(cellprimitivesout&
&   , 1), '×', SIZE(cellprimitivesout, 2)
    DEALLOCATE(cellprimitivesout)
! 释放内存
  END IF
  IF (ALLOCATED(fluxresiduals)) THEN
    DEALLOCATE(fluxresiduals)
  END IF
END program RUN_MAIN_NODIFF

