!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
! 主程序：通过use模块获取main的显式接口
program RUN_MAIN_NODIFF
! 关键：使用包含main的模块，自动获取显式接口
  USE BUFLOWMODULE_DIFF
  IMPLICIT NONE
! 输入参数
  REAL(kind=8) :: data_4d137(1, 4)
!    !$AD INPUT  ! 标记为微分的输入变量（自变量）
  REAL(kind=8), ALLOCATABLE :: cellprimitivesout(:, :)
  INTRINSIC ALLOCATED
  INTRINSIC SIZE
!    real(kind=8), allocatable :: fluxResidualsOut(:,:)
  data_4d137(1, 1) = -0.75d0
!   data_4D137(1,2:4) = 0.0d0  ! 后三个维度固定为0
  data_4d137(1, 2) = 0.485d0
  data_4d137(1, 3) = -0.588d0
! 后三个维度固定为0 
  data_4d137(1, 4) = -0.912d0
! 调用COMPUTE_CFD子程序
  CALL COMPUTE_CFD(cellprimitivesout)
  IF (ALLOCATED(cellprimitivesout)) THEN
    PRINT*, 'CFD计算完成，结果维度：', SIZE(cellprimitivesout&
&   , 1), '×', SIZE(cellprimitivesout, 2)
    DEALLOCATE(cellprimitivesout)
! 释放内存
  END IF
  IF (ALLOCATED(fluxresiduals)) THEN
    DEALLOCATE(fluxresiduals)
  END IF
END program RUN_MAIN_NODIFF

