!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.16 (develop) - 29 Jul 2025 17:17
!
! 主程序：通过use模块获取main的显式接口
program RUN_MAIN_NODIFF
! 关键：使用包含main的模块，自动获取显式接口
  USE MAIN_MODULE_DIFF
  USE TYPESMODULE_DIFF, ONLY: mesh_path_runtime, deformation_mode_runtime, &
& deformation_mode_cylinder, cylinder_axis_ratio_runtime
  IMPLICIT NONE
! 输入参数
  REAL(kind=8) :: data_4d137(1, 4)
!    !$AD INPUT  ! 标记为微分的输入变量（自变量）
  REAL(kind=8), ALLOCATABLE :: cellprimitivesout(:, :)
  INTRINSIC ALLOCATED
  INTRINSIC SIZE
!    real(kind=8), allocatable :: fluxResidualsOut(:,:)
  mesh_path_runtime = 'mesh1'
  deformation_mode_runtime = deformation_mode_cylinder
  cylinder_axis_ratio_runtime = 1.15d0
  data_4d137 = 0.0d0
! 圆柱参数化只使用 data_4d137(1,1)：长短轴比
  data_4d137(1, 1) = cylinder_axis_ratio_runtime
! 调用main子程序（此时编译器已知晓其接口，支持可分配数组参数）
  CALL MAIN(data_4d137, cellprimitivesout)
  IF (ALLOCATED(cellprimitivesout)) THEN
    PRINT*, 'CFD计算完成，结果维度：', SIZE(cellprimitivesout&
&   , 1), '×', SIZE(cellprimitivesout, 2)
    DEALLOCATE(cellprimitivesout)
! 释放内存
  END IF
  IF (ALLOCATED(fluxresiduals)) THEN
    DEALLOCATE(fluxresiduals)
  END IF
END program RUN_MAIN_NODIFF

